-- Besin kataloğunu kapsamlı şekilde genişlet: kahvaltılıklar, meyveler,
-- kuruyemiş/atıştırmalık, sebze yemekleri, ana yemekler, çorbalar, salata/mezeler,
-- süt ürünleri, tatlılar, içecekler, baklagil/tahıl, fast-food.
-- Idempotent: foods.name benzersiz; tekrar çalıştırma çakışmaz.

insert into public.foods (name, unit_label, kcal_per_unit) values
  -- Kahvaltılıklar
  ('Kaymak', 'yemek kaşığı', 55),
  ('Krem peynir', 'yemek kaşığı', 50),
  ('Dil peyniri', 'dilim', 80),
  ('Örgü peyniri', 'dilim', 80),
  ('Mihaliç peyniri', 'dilim', 95),
  ('Ezine peyniri', 'dilim', 80),
  ('Süzme peynir (cottage)', 'porsiyon', 100),
  ('Pastırma', 'dilim', 30),
  ('Salam', 'dilim', 35),
  ('Sosis', 'adet', 120),
  ('Jambon', 'dilim', 30),
  ('Yumurta beyazı', 'adet', 17),
  ('Yumurta sarısı', 'adet', 55),
  ('Sucuklu yumurta', 'porsiyon', 320),
  ('Pastırmalı yumurta', 'porsiyon', 280),
  ('Menemen (sucuklu)', 'porsiyon', 350),
  ('Çılbır', 'porsiyon', 250),
  ('Mıhlama (kuymak)', 'porsiyon', 400),
  ('Kaygana', 'porsiyon', 200),
  ('Gözleme (peynirli)', 'adet', 300),
  ('Gözleme (patatesli)', 'adet', 320),
  ('Peynirli börek', 'dilim', 250),
  ('Su böreği', 'dilim', 280),
  ('Sigara böreği', 'adet', 90),
  ('Açma', 'adet', 230),
  ('Bazlama', 'adet', 180),
  ('Yufka ekmeği', 'adet', 100),
  ('Lavaş', 'adet', 120),
  ('Tost ekmeği', 'dilim', 70),
  ('Kepekli ekmek', 'dilim', 65),
  ('Çavdar ekmeği', 'dilim', 65),
  ('Mısır ekmeği', 'dilim', 75),
  ('Kruvasan', 'adet', 230),
  ('Krep', 'adet', 150),
  ('Pankek', 'adet', 90),
  ('Waffle', 'adet', 250),
  ('Fıstık ezmesi', 'yemek kaşığı', 95),
  ('Çikolatalı fındık kreması', 'yemek kaşığı', 100),
  ('Yumurtalı ekmek', 'dilim', 130),
  ('Zeytin ezmesi', 'yemek kaşığı', 45),
  ('Közlenmiş biber', 'porsiyon', 40),
  ('Acılı ezme (acuka)', 'yemek kaşığı', 30),

  -- Meyveler
  ('Greyfurt', 'adet', 80),
  ('Ananas', 'dilim', 50),
  ('Kivi', 'adet', 45),
  ('Mango', 'adet', 200),
  ('Erik', 'adet', 30),
  ('Vişne', 'kase', 80),
  ('Böğürtlen', 'kase', 60),
  ('Ahududu', 'kase', 60),
  ('Yaban mersini', 'kase', 80),
  ('Dut', 'kase', 60),
  ('Trabzon hurması', 'adet', 120),
  ('Ayva', 'adet', 60),
  ('Nektarin', 'adet', 60),
  ('Limon', 'adet', 20),
  ('Hindistan cevizi', 'dilim', 100),
  ('Kuru incir', 'adet', 47),
  ('Kuru erik', 'adet', 20),
  ('Pestil', 'dilim', 90),

  -- Kuruyemiş & atıştırmalık
  ('Leblebi', 'avuç', 130),
  ('Kabak çekirdeği', 'avuç', 150),
  ('Çam fıstığı', 'yemek kaşığı', 60),
  ('Karışık kuruyemiş', 'avuç', 170),
  ('Fındık ezmesi', 'yemek kaşığı', 95),
  ('Patates cipsi', 'paket', 150),
  ('Mısır cipsi', 'avuç', 140),
  ('Kraker', 'adet', 15),
  ('Galeta', 'adet', 30),
  ('Grissini', 'adet', 20),
  ('Mısır patlağı (popcorn)', 'kase', 120),

  -- Zeytinyağlı & sebze yemekleri
  ('Zeytinyağlı taze fasulye', 'porsiyon', 120),
  ('Zeytinyağlı barbunya', 'porsiyon', 180),
  ('Zeytinyağlı enginar', 'adet', 120),
  ('Zeytinyağlı pırasa', 'porsiyon', 130),
  ('Zeytinyağlı kereviz', 'porsiyon', 110),
  ('Zeytinyağlı bamya', 'porsiyon', 120),
  ('Kabak yemeği', 'porsiyon', 120),
  ('Patlıcan yemeği', 'porsiyon', 160),
  ('Mücver', 'adet', 80),
  ('Musakka', 'porsiyon', 230),
  ('Biber dolması (zeytinyağlı)', 'adet', 90),
  ('Lahana sarma', 'adet', 40),
  ('Kabak dolması', 'adet', 100),
  ('Etli biber dolması', 'adet', 120),

  -- Ana yemekler (et / tavuk)
  ('Tavuk şiş', 'porsiyon', 250),
  ('Tavuk pirzola', 'adet', 200),
  ('Tavuk kanat', 'adet', 100),
  ('Tavuk sote', 'porsiyon', 250),
  ('Adana kebap', 'porsiyon', 400),
  ('Urfa kebap', 'porsiyon', 380),
  ('Beyti kebap', 'porsiyon', 450),
  ('İskender', 'porsiyon', 600),
  ('Kuzu pirzola', 'adet', 150),
  ('Et sote', 'porsiyon', 300),
  ('Tas kebabı', 'porsiyon', 320),
  ('Et güveç', 'porsiyon', 300),
  ('Hünkar beğendi', 'porsiyon', 380),
  ('İzmir köfte', 'porsiyon', 300),
  ('Şiş köfte', 'porsiyon', 350),
  ('Çiğ köfte (etsiz)', 'porsiyon', 150),
  ('Etli pilav', 'porsiyon', 420),
  ('Tavuklu pilav', 'porsiyon', 400),
  ('Nohutlu pilav', 'porsiyon', 350),
  ('Şehriyeli pilav', 'kase', 230),
  ('İç pilav', 'porsiyon', 280),

  -- Makarna & hamur
  ('Spagetti', 'porsiyon', 250),
  ('Fırın makarna', 'porsiyon', 350),
  ('Penne arabiata', 'porsiyon', 320),
  ('Lazanya', 'porsiyon', 400),

  -- Fast food / sokak lezzetleri
  ('Pizza', 'dilim', 280),
  ('Hamburger', 'adet', 500),
  ('Çizburger', 'adet', 550),
  ('Tavuk burger', 'adet', 450),
  ('Tavuk nugget', 'adet', 50),
  ('Kumpir', 'adet', 500),
  ('Kaşarlı tost', 'adet', 300),
  ('Ayvalık tostu', 'adet', 450),
  ('Tavuklu sandviç', 'adet', 350),
  ('Tavuk dürüm', 'adet', 400),
  ('Et döner', 'porsiyon', 400),
  ('Tantuni', 'porsiyon', 350),
  ('Köfte ekmek', 'adet', 400),
  ('Balık ekmek', 'adet', 350),

  -- Deniz ürünleri
  ('Midye dolma', 'adet', 25),
  ('Kalamar tava', 'porsiyon', 250),
  ('Karides güveç', 'porsiyon', 200),
  ('Hamsi tava', 'porsiyon', 280),
  ('Levrek ızgara', 'porsiyon', 180),
  ('Çipura ızgara', 'porsiyon', 200),
  ('Alabalık', 'porsiyon', 180),
  ('Uskumru ızgara', 'porsiyon', 250),

  -- Çorbalar
  ('Tarhana çorbası', 'kase', 130),
  ('Yayla çorbası', 'kase', 140),
  ('İşkembe çorbası', 'kase', 180),
  ('Mantar çorbası', 'kase', 130),
  ('Brokoli çorbası', 'kase', 120),
  ('Balık çorbası', 'kase', 150),
  ('Düğün çorbası', 'kase', 180),

  -- Salata & mezeler
  ('Yeşil salata', 'kase', 40),
  ('Gavurdağı salatası', 'porsiyon', 120),
  ('Patates salatası', 'porsiyon', 200),
  ('Rus salatası', 'porsiyon', 250),
  ('Cacık', 'kase', 80),
  ('Haydari', 'yemek kaşığı', 40),
  ('Humus', 'yemek kaşığı', 50),
  ('Şakşuka', 'porsiyon', 150),
  ('Közlenmiş patlıcan salatası', 'porsiyon', 120),
  ('Fava', 'porsiyon', 130),
  ('Piyaz', 'porsiyon', 180),
  ('Kısır', 'porsiyon', 180),
  ('Babagannuş', 'yemek kaşığı', 40),
  ('Deniz börülcesi', 'porsiyon', 60),
  ('Turşu', 'porsiyon', 20),

  -- Süt ürünleri
  ('Süzme yoğurt', 'kase (150 g)', 120),
  ('Light yoğurt', 'kase (150 g)', 70),
  ('Yarım yağlı süt', 'bardak', 90),
  ('Yağsız süt', 'bardak', 70),
  ('Çikolatalı süt', 'bardak', 180),
  ('Badem sütü', 'bardak', 40),
  ('Soya sütü', 'bardak', 80),
  ('Yulaf sütü', 'bardak', 90),
  ('Mozzarella', 'dilim', 80),
  ('Cheddar peyniri', 'dilim', 110),
  ('Parmesan', 'yemek kaşığı', 25),

  -- Baklagil & tahıl
  ('Yeşil mercimek yemeği', 'porsiyon', 200),
  ('Barbunya pilaki', 'porsiyon', 180),
  ('Kinoa', 'porsiyon', 180),
  ('Karabuğday', 'porsiyon', 170),
  ('Kuskus', 'porsiyon', 180),
  ('Haşlanmış mısır', 'adet', 100),
  ('Bezelye yemeği', 'porsiyon', 120),
  ('Bakla yemeği', 'porsiyon', 110),
  ('Edamame', 'porsiyon', 120),
  ('Tofu', '100 g', 80),
  ('Falafel', 'adet', 60),

  -- Tatlılar
  ('Künefe', 'porsiyon', 350),
  ('Kazandibi', 'kase', 220),
  ('Tavuk göğsü tatlısı', 'kase', 200),
  ('Profiterol', 'porsiyon', 350),
  ('Tiramisu', 'porsiyon', 300),
  ('Cheesecake', 'dilim', 350),
  ('Magnolia', 'kase', 250),
  ('Dondurma', 'top', 80),
  ('Aşure', 'kase', 250),
  ('Güllaç', 'porsiyon', 200),
  ('Revani', 'dilim', 250),
  ('Şekerpare', 'adet', 120),
  ('Tulumba', 'adet', 80),
  ('Lokma', 'adet', 40),
  ('Helva', 'dilim', 250),
  ('İrmik helvası', 'porsiyon', 280),
  ('Brownie', 'adet', 250),
  ('Kurabiye', 'adet', 80),
  ('Bisküvi', 'adet', 45),
  ('Çikolatalı gofret', 'adet', 130),
  ('Sütlü çikolata', 'kare', 55),
  ('Lokum', 'adet', 50),
  ('Sade kek', 'dilim', 200),
  ('Kakaolu kek', 'dilim', 230),

  -- İçecekler
  ('Su', 'bardak', 0),
  ('Maden suyu', 'şişe', 0),
  ('Meyveli soda', 'şişe', 60),
  ('Kola', 'kutu', 140),
  ('Kola (light)', 'kutu', 1),
  ('Gazoz', 'şişe', 120),
  ('Enerji içeceği', 'kutu', 110),
  ('Buzlu çay', 'bardak', 90),
  ('Sıcak çikolata', 'bardak', 190),
  ('Salep', 'bardak', 200),
  ('Latte', 'bardak', 120),
  ('Cappuccino', 'bardak', 110),
  ('Espresso', 'fincan', 5),
  ('Americano', 'bardak', 10),
  ('Smoothie', 'bardak', 180),
  ('Taze portakal suyu', 'bardak', 110),
  ('Şalgam suyu', 'bardak', 30),
  ('Boza', 'bardak', 200)
on conflict (name) do nothing;
